from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from kifrs.feedback import CaseIntake, ReviewerCorrection
from kifrs.feedback.queue import write_queue
from kifrs.feedback.transaction_poc import build_transaction_poc_package


DEFAULT_OUT = Path("docs/reports/real-transaction-poc")


def sample_case() -> CaseIntake:
    return CaseIntake(
        case_id="anon-lease-poc-001",
        domain_hint="KIFRS1116",
        anonymized_title="Anonymized office lease",
        fact_pattern_summary="Sanitized office lease facts prepared as a structured PoC card.",
        structured_facts={
            "party": "lessee",
            "lease_term": "4 years",
            "payment_schedule": "annual arrears",
            "lease_term_years": 4,
            "annual_payment": 1_000_000,
            "discount_rate": 0.05,
            "annuity_factor": 3.54595,
            "payment_timing": "arrears",
        },
        requested_outputs=[
            "review_pack",
            "journal_entry_draft",
            "disclosure_questions",
            "human_review_questions",
        ],
        source_boundaries=[
            "contract clauses are summarized into structured facts",
            "reviewer checks original documents outside this repo",
        ],
        reviewer_questions=[
            "Does the lease term evidence support four years?",
            "Are there variable lease payments or extension options outside the structured card?",
        ],
    )


def sample_correction() -> ReviewerCorrection:
    return ReviewerCorrection(
        case_id="anon-lease-poc-001",
        issue="Lease term evidence question should be explicit",
        severity="medium",
        suggested_fix="Add a required reviewer question for lease term evidence.",
        missing_evidence=["lease term approval evidence"],
        disposition="eval_seed_candidate",
        affected_outputs=["human_review_questions", "review_pack"],
    )


def write_package(out: Path) -> dict[str, Path]:
    package = build_transaction_poc_package(sample_case(), sample_correction())
    out.mkdir(parents=True, exist_ok=True)

    paths = {
        "index": out / "INDEX.md",
        "input_card": out / "anonymized-input-card.md",
        "review_pack": out / "review-pack.md",
        "queue_jsonl": out / "feedback-queue.jsonl",
        "queue_report": out / "feedback-queue-report.md",
        "package_manifest": out / "package-manifest.json",
    }
    paths["input_card"].write_text(package.input_card_markdown, encoding="utf-8")
    paths["review_pack"].write_text(package.review_pack_markdown, encoding="utf-8")
    write_queue(paths["queue_jsonl"], [package.queue_record])
    paths["queue_report"].write_text(package.queue_report_markdown, encoding="utf-8")
    paths["package_manifest"].write_text(
        json.dumps(
            {
                "case_id": package.case.case_id,
                "domain": package.case.domain_hint,
                "review_pack_status": package.review_pack.status,
                "queue_records": 1,
                "public_safe": True,
                "files": {key: str(path.as_posix()) for key, path in paths.items() if key != "index"},
            },
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    paths["index"].write_text(render_index(paths, package.review_pack.status), encoding="utf-8")
    return paths


def render_index(paths: dict[str, Path], review_pack_status: str) -> str:
    return "\n".join(
        [
            "# Real Anonymized Transaction PoC Package",
            "",
            "> Public-safe sample generated from one anonymized F-ACC transaction card.",
            "",
            "## Summary",
            "",
            "- Domain: KIFRS1116",
            "- Target service-line: F-ACC Accounting Advisory / F-S support",
            f"- Review pack status: {review_pack_status}",
            "- Queue records: 1 eval seed candidate",
            "",
            "## Files",
            "",
            f"1. `{paths['input_card'].name}` - sanitized structured transaction card",
            f"2. `{paths['review_pack'].name}` - F-ACC review pack generated by the existing 1116 pipeline",
            f"3. `{paths['queue_jsonl'].name}` - public-safe feedback queue record",
            f"4. `{paths['queue_report'].name}` - queue report for reviewer correction",
            f"5. `{paths['package_manifest'].name}` - machine-readable package manifest",
            "",
            "## Boundary",
            "",
            "- This package uses synthetic anonymized facts for public verification.",
            "- It does not include copied contract text, customer identifiers, private filings, parsed standards, embeddings, or workpaper payloads.",
            "- The review pack is a decision-prep draft, not a final accounting conclusion.",
            "",
            "## Regeneration",
            "",
            "```powershell",
            "python scripts\\real_transaction_poc.py --out docs\\reports\\real-transaction-poc",
            "```",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a public-safe real anonymized transaction PoC package.")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    paths = write_package(args.out)
    print(f"wrote {paths['index'].parent}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
